name: 'Deploy to AWS S3'
description: 'Deploy files to AWS S3'
inputs:
  bucket:
    description: 'The S3 bucket to deploy to'
    required: true
  region:
    description: 'The AWS region to deploy to'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder to deploy'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
